### ISSUE TITLE
Update Schedule for Fall 2023

### ISSUE THREAD

**Issue by MicheleTobias** [maptimedavis/maptimedavis.github.io#3]
The events post needs to be updated with the upcoming schedule.

- [ ] Add details to the table
- [ ] Create registration links 
- [ ] Create Calendar items on DataLab's website (including registration link)
- [ ] Add calendar links to the table

**Comment by MicheleTobias** [comment]
I added the workshops we currently know about to the Events page table. There's still more work to be done once we can get into the registration system next week.

**Comment by bhavuk2002** [comment]
What this project is about? I unable to understand. Could you please elaborate? I want to contribute more this seem interesting and doable.

**Comment by MicheleTobias** [comment]
@bhavuk2002  This repo is for the website for a community mapping workshop series called #maptimeDavis. This is a task for members of the advisory board to work on. It lists the tasks we need to do to allow people to register to attend the workshops on our schedule.

**Comment by bhavuk2002** [comment]
okay, if you need any help in a task, i would love to contribute. I would just require a minimal guidance as im familiar with JS and Node.

PS: already setup the environment for the project on my local machine.
